export const studiesEs = [
  {
    id: 1,
    institution: "ACADEMLO",
    date: "2022-2023",
    description: "Programa Full Stack de Desarollo",
    img: "./img/logo_academlo.png",
    link: "https://certificates.academlo.com/en/verify/40809561884902",
  },
  {
    id: 2,
    institution: "ACADEMLO",
    date: "2023-2023",
    description: "Desarrollador Back-End con Node.js",
    img: "./img/logo_academlo.png",
    link: "https://certificates.academlo.com/en/verify/65429460793044",
  },
  {
    id: 3,
    institution: "ACADEMLO",
    date: "2023-2023",
    description: "Desarrollo de aplicaciones web con React",
    img: "./img/logo_academlo.png",
    link: "https://certificates.academlo.com/en/verify/08034945405880",
  },
  {
    id: 4,
    institution: "Código Facilito",
    date: "2023-2023",
    description: "Curso Profesional de JavaScript",
    img: "./img/codigo_facilito.png",
    link: "https://drive.google.com/file/d/18pTxK68klnDtdI6F4gxI3qshKUY-IRUC/view?usp=drive_link",
  },
  {
    id: 5,
    institution: "Código Facilito",
    date: "2023-2023",
    description: "Curso Profesional de Base de Datos",
    img: "./img/codigo_facilito.png",
    link: "https://drive.google.com/file/d/1ur_tjmYoUaobQR8zMIHxJCETpddZxc0M/view?usp=sharing",
  },
  {
    id: 6,
    institution: "Código Facilito",
    date: "2023-2023",
    description: "Curso Profesional de Backend",
    img: "./img/codigo_facilito.png",
    link: "https://drive.google.com/file/d/1-ZPzVYMSCBb5We0rAsHxgaqKzX6db-We/view?usp=sharing",
  },
  {
    id: 7,
    institution: "Código Facilito",
    date: "2023-2023",
    description: "Curso a fondo de GitHub",
    img: "./img/codigo_facilito.png",
    link: "https://drive.google.com/file/d/1BzWBIsxoXkFB-AE2KAxdKrIJHvcWVU0O/view?usp=sharing",
  },
  {
    id: 8,
    institution: "Código Facilito",
    date: "2023-2023",
    description: "Curso de Introducción a Tailwind",
    img: "./img/codigo_facilito.png",
    link: "https://drive.google.com/file/d/1ZH-fc9Jo1a_ZWrQ9XhbpN8ek3ZbcBKg6/view?usp=sharing",
  },
  {
    id: 9,
    institution: "Código Facilito",
    date: "2023-2023",
    description: "Curso de TypeScript",
    img: "./img/codigo_facilito.png",
    link: "https://drive.google.com/file/d/1gEUrQu6knwEnjZdLpG8of1BF41dEjChn/view?usp=sharing",
  },
  {
    id: 10,
    institution: "Platzi",
    date: "2023-2023",
    description: "Curso de Programación Básica",
    img: "./img/platzi.webp",
    link: "https://drive.google.com/file/d/1nMk0c1b1NiPdpoUNasLNM_p3B-QvQeQe/view?usp=drive_link",
  },
  {
    id: 11,
    institution: "ACADEMLO",
    date: "2022-2023",
    description: "Fundamentos de desarrollo web",
    img: "./img/logo_academlo.png",
    link: "https://certificates.academlo.com/en/verify/48003017235387",
  },
  {
    id: 12,
    institution: "Microsoft",
    date: "2020-2020",
    description: "Certificación Internacional de Analista de Datos Asociado ",
    img: "./img/Microsoft-logo.jpg",
    link: "https://drive.google.com/file/d/1iFz4zu58L1fLB10hEnspK2quRdAl1dYX/view?usp=drive_link",
  },
  {
    id: 13,
    institution: "CEABAD",
    date: "2020-2020",
    description: "Internet de las Cosas",
    img: "./img/ceabad.jpg",
    link: "https://drive.google.com/file/d/1B8x9gTxd2WZQ3HjdRPgJsb9HX72n_faC/view?usp=drive_link",
  },
  {
    id: 14,
    institution: "Universidad URACCAN",
    date: "2012-2016",
    description: "Licenciatura en Informática Administrativa",
    img: "./img/uraccan.png",
    link: "https://drive.google.com/file/d/1SiujntM2O8GsmpFcj3f6RrO3BjKI3dO7/view?usp=drive_link",
  },
];

export const studiesEN = [
  {
    id: 1,
    institution: "ACADEMLO",
    date: "2022-2023",
    description: "Full Stack Web Development",
    img: "./img/logo_academlo.png",
    link: "https://certificates.academlo.com/en/verify/40809561884902",
  },
  {
    id: 2,
    institution: "ACADEMLO",
    date: "2023-2023",
    description: "Back-End Development with Node.js",
    img: "./img/logo_academlo.png",
    link: "https://certificates.academlo.com/en/verify/65429460793044",
  },
  {
    id: 3,
    institution: "Academlo",
    date: "2023-2023",
    description: "Web application development with React",
    img: "./img/logo_academlo.png",
    link: "https://certificates.academlo.com/en/verify/08034945405880",
  },
  {
    id: 4,
    institution: "Easy code",
    date: "2023-2023",
    description: "Professional JavaScript Course",
    img: "./img/codigo_facilito.png",
    link: "https://drive.google.com/file/d/18pTxK68klnDtdI6F4gxI3qshKUY-IRUC/view?usp=drive_link",
  },
  {
    id: 5,
    institution: "Easy code",
    date: "2023-2023",
    description: "Professional Database Course",
    img: "./img/codigo_facilito.png",
    link: "https://drive.google.com/file/d/1ur_tjmYoUaobQR8zMIHxJCETpddZxc0M/view?usp=sharing",
  },
  {
    id: 6,
    institution: "Easy code",
    date: "2023-2023",
    description: "Professional Backend Course",
    img: "./img/codigo_facilito.png",
    link: "https://drive.google.com/file/d/1-ZPzVYMSCBb5We0rAsHxgaqKzX6db-We/view?usp=sharing",
  },
  {
    id: 7,
    institution: "Easy code",
    date: "2023-2023",
    description: "In-depth GitHub Course",
    img: "./img/codigo_facilito.png",
    link: "https://drive.google.com/file/d/1BzWBIsxoXkFB-AE2KAxdKrIJHvcWVU0O/view?usp=sharing",
  },
  {
    id: 8,
    institution: "Easy code",
    date: "2023-2023",
    description: "Introduction to Tailwind Course",
    img: "./img/codigo_facilito.png",
    link: "https://drive.google.com/file/d/1ZH-fc9Jo1a_ZWrQ9XhbpN8ek3ZbcBKg6/view?usp=sharing",
  },
  {
    id: 9,
    institution: "Easy code",
    date: "2023-2023",
    description: "TypeScript Course",
    img: "./img/codigo_facilito.png",
    link: "https://drive.google.com/file/d/1gEUrQu6knwEnjZdLpG8of1BF41dEjChn/view?usp=sharing",
  },
  {
    id: 10,
    institution: "Platzi",
    date: "2023-2023",
    description: "Basic Programming Course",
    img: "./img/platzi.webp",
    link: "https://drive.google.com/file/d/1nMk0c1b1NiPdpoUNasLNM_p3B-QvQeQe/view?usp=drive_link",
  },
  {
    id: 11,
    institution: "Academlo",
    date: "2022-2023",
    description: "Fundamentals of web development",
    img: "./img/logo_academlo.png",
    link: "https://certificates.academlo.com/en/verify/48003017235387",
  },

  {
    id: 12,
    institution: "Microsoft",
    date: "2020-2020",
    description: "International Certification Data Analyst Associate",
    img: "./img/Microsoft-logo.jpg",
    link: "https://drive.google.com/file/d/1iFz4zu58L1fLB10hEnspK2quRdAl1dYX/view?usp=drive_link",
  },
  {
    id: 13,
    institution: "CEABAD",
    date: "2020-2020",
    description: "Internet of Things (IoT)",
    img: "./img/ceabad.jpg",
    link: "https://drive.google.com/file/d/1B8x9gTxd2WZQ3HjdRPgJsb9HX72n_faC/view?usp=drive_link",
  },
  {
    id: 14,
    institution: " URACCAN University",
    date: "2012-2016",
    description: "Bachelor's Degree in Administrative Informatics",
    img: "./img/uraccan.png",
    link: "https://drive.google.com/file/d/1SiujntM2O8GsmpFcj3f6RrO3BjKI3dO7/view?usp=drive_link",
  },
];
